name: Test and Lint Frontends

on:
  push:
    branches: main

  pull_request:
    branches: main
  
env:
  NODE_VERSION: "lts/*"

jobs:
  lint:
    name: Running linter
    # Don't run on draft pull requests
    # if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages:
          - dapp-template/frontend
          - euroe-demo
          - gallery
          - low-code-nft-marketplace/common-ui
          - low-code-nft-marketplace/market-ui
          - low-code-nft-marketplace/mint-ui
          - sponsoredTransactions/frontend
          - sponsoredTransactionsAuction/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        if: ${{ matrix.packages == 'low-code-nft-marketplace/market-ui' || matrix.packages == 'low-code-nft-marketplace/mint-ui' }}
        run: cd low-code-nft-marketplace/common-ui && yarn install

      - name: Run install
        run: cd ${{ matrix.packages }} && yarn install

      - name: Run Lint
        run: cd ${{ matrix.packages }} && yarn lint
      